### ISSUE TITLE
Structure explorer doesn't import its own exports

### ISSUE THREAD

**Issue by marcel3032** [FMFI-UK-1-AIN-412/structure-explorer#6]
If I export json without formulas (e.g. `{"common":{"teacherMode":false},"language":{"constants":{"value":"a,b","locked":false,"errorMessage":"","parsed":["a","b"]},"predicates":{"value":"likes/2","locked":false,"errorMessage":"","parsed":[{"name":"likes","arity":2}]},"functions":{"value":"","locked":false,"errorMessage":"","parsed":[]},"lockedComponent":false},"structure":{"constants":{"a":{"value":"1","locked":false,"errorMessage":"","parsed":[]},"b":{"value":"2","locked":false,"errorMessage":"","parsed":[]}},"predicates":{"likes/2":{"value":"","locked":false,"errorMessage":"","parsed":[],"tableEnabled":false}},"functions":{},"variables":{"value":"","locked":false,"errorMessage":"","parsed":[],"object":{}},"domain":{"value":"1,2","locked":false,"errorMessage":"","parsed":["1","2"]}},"expressions":{"formulas":[],"terms":[]},"diagramCordState":{}}` )  structure explorer will accept it and open it.

But, when i add some formula, to explore if it is satifisfied (e.g. `{"common":{"teacherMode":false},"language":{"constants":{"value":"a,b","locked":false,"errorMessage":"","parsed":["a","b"]},"predicates":{"value":"likes/2","locked":false,"errorMessage":"","parsed":[{"name":"likes","arity":2}]},"functions":{"value":"","locked":false,"errorMessage":"","parsed":[]},"lockedComponent":false},"structure":{"constants":{"a":{"value":"1","locked":false,"errorMessage":"","parsed":[]},"b":{"value":"2","locked":false,"errorMessage":"","parsed":[]}},"predicates":{"likes/2":{"value":"","locked":false,"errorMessage":"","parsed":[],"tableEnabled":false}},"functions":{},"variables":{"value":"","locked":false,"errorMessage":"","parsed":[],"object":{}},"domain":{"value":"1,2","locked":false,"errorMessage":"","parsed":["1","2"]}},"expressions":{"formulas":[{"value":"likes(a,b)","expressionValue":false,"answerValue":true,"errorMessage":"","inputLocked":false,"answerLocked":false,"gameEnabled":false,"parsed":{"name":"likes","terms":[{"name":"a"},{"name":"b"}]},"gameCommitment":null,"gameHistory":[],"gameVariables":{},"gameValue":null,"showVariables":false,"validSyntax":true}],"terms":[]},"diagramCordState":{}}` )

It won´t open it, and there JavaScript Error raise `Uncaught TypeError: r.gameVariables is not iterable`

![image](https://user-images.githubusercontent.com/18122517/109164632-f1b7c480-777a-11eb-91a3-4da71edf9403.png)

**Comment by crnkjck** [comment]
This should be resolved now.
